spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/v1/auth/**
        - id: credit-service
          uri: lb://CREDITS-SERVICE
          predicates:
            - Path=/api/v1/credit/**
          filters:
            - AuthenticationFilter
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - AuthenticationFilter
        - id: interest-service
          uri: lb://INTEREST-SERVICE
          predicates:
            - Path=/api/v1/interest/**
          filters:
            - AuthenticationFilter
management:
  tracing:
    sampling:
      probability: 1.0 # only for testing purpose, switch back to 0.1 for production code
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka


application:
  security:
    jwt:
      secret-key: DEFINESOMESECRETKEYTOSINGTOKENFORSECURINGAPPLICATIONWITHJWTTOKEN
      #      expiration: 60000 # 1 min
      #      expiration: 900000 # 15 mins
      expiration: 86400000 # 1 day

server:
  port: 8222