spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://config-server:8888/
#    label: docker
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        format_sql: true
#        boot:
#          allow_jdbc_metadata_access: false
#    show-sql: true
#  cloud:
#    config:
#      enabled: true
#
#
#
#server:
#  port: 8761
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://discovery-server:8761/eureka
#  instance:
#    hostname: discovery-server
#    port: 8761
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#
#application:
#  security:
#    jwt:
#      secret-key: DEFINESOMESECRETKEYTOSINGTOKENFORSECURINGAPPLICATIONWITHJWTTOKEN
#      #      expiration: 60000 # 1 min
#      #      expiration: 900000 # 15 mins
#      expiration: 86400000 # 1 day
