eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
    show-sql: true


application:
  security:
    jwt:
      secret-key: DEFINESOMESECRETKEYTOSINGTOKENFORSECURINGAPPLICATIONWITHJWTTOKEN
#      expiration: 60000 # 1 min
#      expiration: 900000 # 15 mins
      expiration: 86400000 # 1 day
