server:
  port: 8090

spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/credits
    username: postgres
    password: 123456

application:
  security:
    jwt:
      secret-key: DEFINESOMESECRETKEYTOSINGTOKENFORSECURINGAPPLICATIONWITHJWTTOKEN
      expiration: 60000 # 1 min
#      expiration: 900000 # 15 mins
