server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/v1/auth/**
        - id: credit-service
          uri: lb://CREDITS-SERVICE
          predicates:
            - Path=/api/v1/credit/**
          filters:
            - AuthenticationFilter
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - AuthenticationFilter
        - id: interest-service
          uri: lb://INTEREST-SERVICE
          predicates:
            - Path=/api/v1/interest/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
