server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/v1/auth/**
        - id: credit-service
          uri: lb://CREDITS-SERVICE
          predicates:
            - Path=/api/v1/credit/**

eureka:
  client:
    register-with-eureka: true
