spring:
  application:
    name: config-server
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/configurations
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mcorekci37/credit-app
          search-paths: config-server/src/main/resources/configurations
#          clone-on-start: true

server:
  port: 8888