spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mcorekci37/credit-config-repo
          clone-on-start: true
#          default-label: docker
  zipkin:
    base-url: http://zipkin:9411
server:
  port: 8888
